defaults:
  - agent: ppo
  - agent/ppo/policy: xtma_beta
  - agent/ppo/training: ppo
  - agent/ppo/obs_configs: birdview
  - test_suites: nocrash_dense
actors:
  hero:
    agent: ppo
    reward:
      entry_point: reward.valeo_action:ValeoAction
    terminal:
      entry_point: terminal.leaderboard:Leaderboard
agent:
  ppo:
    ckpt: checkpoints/roach_rl/ckpt/ckpt_11833344.pth
carla_sh_path: null
log_level: INFO
host: localhost
port: 2000
seed: 2021
no_rendering: false
kill_running: true
resume: true
wb_project: debug
wb_notes: null
wb_group: null
wb_tags: null
log_video: true
